version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: standart-kalip-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - FRONTEND_URL=https://decayazilim.com.tr
    volumes:
      - ./backend/uploads:/app/backend/uploads
    networks:
      - standart-kalip-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: standart-kalip-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VITE_API_BASE_URL=https://api.decayazilim.com.tr
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - standart-kalip-network
    depends_on:
      - backend

  mongodb:
    image: mongo:6.0
    container_name: standart-kalip-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=standart_kalip
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/init:/docker-entrypoint-initdb.d:ro
    networks:
      - standart-kalip-network

volumes:
  mongodb_data:
    driver: local

networks:
  standart-kalip-network:
    driver: bridge
